name: RK-Protection
author: T4TU_
version: 2
main: me.t4tu.rkprotection.Protection
depend: [RK-Core]
api-version: 1.13
commands:
    pvpbypass:
    area:
    lukko:
    lukitse:
    avaa:
    oikeudet:
    bypass: