package me.t4tu.rkprotection.areas;

public enum Flag {
	
	PVP, NO_MOBS, NO_ANIMALS, ALLOW_BUILDING, ALLOW_DESTROYING, ALLOW_MISC_INTERACTION, ALLOW_BLOCK_INTERACTION, ALLOW_CONTAINERS, ALLOW_DOORS, ALLOW_TRAPDOORS, ALLOW_FENCE_GATES, 
	ALLOW_REDSTONE, ALLOW_LOCKING, NO_HUNGER, HIDE_MESSAGES, SHOW_PVP_MESSAGE, SHOW_PROTECTED_MESSAGE, HIDE_LOCK_MESSAGES, THRONE, STARTING_AREA
}